import { Badge } from '../../types';
import { SOCKET_SERVER_URL } from '../../config';

const baseUrl = SOCKET_SERVER_URL;

const staticImages: Badge[] = [
  { id: 1,   name: 'abv boadilla',                          url: `${baseUrl}/images/teams/abv-boadilla.jpg.jpeg` },
  { id: 2,   name: 'ad estrecho tetuan',                    url: `${baseUrl}/images/teams/ad-estrecho-tetuan.jpg.jpeg` },
  { id: 3,   name: 'ad joigny',                             url: `${baseUrl}/images/teams/ad-joigny.jpg.jpeg` },
  { id: 4,   name: 'ad perales del rio',                    url: `${baseUrl}/images/teams/ad-perales-del-rio.jpg.jpeg` },
  { id: 5,   name: 'ad voleibol rivas',                     url: `${baseUrl}/images/teams/ad-voleibol-rivas.jpg.jpeg` },
  { id: 6,   name: 'ade salesianos estrecho',               url: `${baseUrl}/images/teams/ade-salesianos-estrecho.png` },
  { id: 7,   name: 'agrupacion padre manyanet',             url: `${baseUrl}/images/teams/agrupacion-padre-manyanet.jpg.jpeg` },
  { id: 8,   name: 'ancora galapagar',                      url: `${baseUrl}/images/teams/ancora-galapagar.jpg.jpeg` },
  { id: 9,   name: 'arcangel international',                url: `${baseUrl}/images/teams/arcangel-international.png` },
  { id: 10,  name: 'arcangel rafael',                       url: `${baseUrl}/images/teams/arcangel-rafael.jpg` },
  { id: 11,  name: 'block out beach volley',                url: `${baseUrl}/images/teams/block-out-beach-volley.jpg.jpeg` },
  { id: 12,  name: 'boadilla m 2 de mayo',                  url: `${baseUrl}/images/teams/boadilla%20m%202%20de%20mayo.jpg` },
  { id: 13,  name: 'cd ciudad de los muchachos',            url: `${baseUrl}/images/teams/cd-ciudad-de-los-muchachos.jpg.jpeg` },
  { id: 14,  name: 'cd dosa',                               url: `${baseUrl}/images/teams/cd-dosa.jpg.jpeg` },
  { id: 15,  name: 'cd educa play',                         url: `${baseUrl}/images/teams/cd-educa-play.jpg.jpeg` },
  { id: 16,  name: 'cd gredos san diego',                   url: `${baseUrl}/images/teams/cd-gredos-san-diego.jpg.jpeg` },
  { id: 17,  name: 'cd kolbe',                              url: `${baseUrl}/images/teams/cd-kolbe.jpg` },
  { id: 18,  name: 'cd loreto madrid',                      url: `${baseUrl}/images/teams/cd-loreto-madrid.jpg.jpeg` },
  { id: 19,  name: 'cd newman',                             url: `${baseUrl}/images/teams/cd-newman.jpg.jpeg` },
  { id: 20,  name: 'cd san agustin los negrales',           url: `${baseUrl}/images/teams/cd-san-agustin-los-negrales.jpg` },
  { id: 21,  name: 'cd san ignacio torrelodones',           url: `${baseUrl}/images/teams/cd-san-ignacio-torrelodones.jpg.jpeg` },
  { id: 22,  name: 'cd san patricio',                       url: `${baseUrl}/images/teams/cd-san-patricio.jpg.jpeg` },
  { id: 23,  name: 'cd sek ciudalcampo',                    url: `${baseUrl}/images/teams/cd-sek-ciudalcampo.jpg.jpeg` },
  { id: 24,  name: 'cd sek el castillo',                    url: `${baseUrl}/images/teams/cd-sek-el-castillo.jpg.jpeg` },
  { id: 25,  name: 'cd vallecas',                           url: `${baseUrl}/images/teams/cd-vallecas.jpg.jpeg` },
  { id: 26,  name: 'cdb avp academia voleibol parla',       url: `${baseUrl}/images/teams/cdb-avp-academia-voleibol-parla.jpg` },
  { id: 27,  name: 'cdb grupo deportivo las rozas',         url: `${baseUrl}/images/teams/cdb-grupo-deportivo-las-rozas.jpg.jpeg` },
  { id: 28,  name: 'cdb las nieves sports',                 url: `${baseUrl}/images/teams/cdb-las-nieves-sports.jpg` },
  { id: 29,  name: 'cde amet',                              url: `${baseUrl}/images/teams/cde-amet.png` },
  { id: 30,  name: 'cde aquila',                            url: `${baseUrl}/images/teams/cde-aquila.jpg.jpeg` },
  { id: 31,  name: 'cde arganvoley',                        url: `${baseUrl}/images/teams/cde-arganvoley.jpg.jpeg` },
  { id: 32,  name: 'cde asuncion',                          url: `${baseUrl}/images/teams/cde-asuncion.jpg.jpeg` },
  { id: 33,  name: 'cde chamartin vergara 1995',            url: `${baseUrl}/images/teams/cde-chamartin-vergara-1995.png` },
  { id: 34,  name: 'cde everest school',                    url: `${baseUrl}/images/teams/cde-everest-school.jpg.jpeg` },
  { id: 35,  name: 'cde highlands el encinar',              url: `${baseUrl}/images/teams/cde-highlands-el-encinar.jpg.jpeg` },
  { id: 36,  name: 'cde intervoley fuenlabrada',            url: `${baseUrl}/images/teams/cde-intervoley-fuenlabrada.jpg.jpeg` },
  { id: 37,  name: 'cde manzanares voley',                  url: `${baseUrl}/images/teams/cde-manzanares-voley.jpg.jpeg` },
  { id: 38,  name: 'cde mostoles 2 de mayo',                url: `${baseUrl}/images/teams/cde-mostoles-2-de-mayo.jpg.jpeg` },
  { id: 39,  name: 'cde parla voley',                       url: `${baseUrl}/images/teams/cde-parla-voley.jpg.jpeg` },
  { id: 40,  name: 'cde polideportivo los molinos',         url: `${baseUrl}/images/teams/cde-polideportivo-los-molinos.jpg.jpeg` },
  { id: 41,  name: 'cde san jaime',                         url: `${baseUrl}/images/teams/cde-san-jaime.jpg.jpeg` },
  { id: 42,  name: 'cde sanagus team voley',                url: `${baseUrl}/images/teams/cde-sanagus-team-voley.jpg.jpeg` },
  { id: 43,  name: 'cde switch volley',                     url: `${baseUrl}/images/teams/cde-switch-volley.jpg.jpeg` },
  { id: 44,  name: 'cde villa de ajalvir',                  url: `${baseUrl}/images/teams/cde-villa-de-ajalvir.jpg.jpeg` },
  { id: 45,  name: 'cde voleibol algete',                   url: `${baseUrl}/images/teams/cde-voleibol-algete.jpg.jpeg` },
  { id: 46,  name: 'cde voleibol getafe',                   url: `${baseUrl}/images/teams/cde-voleibol-getafe.jpg.jpeg` },
  { id: 47,  name: 'cde voleibol hispano usera',            url: `${baseUrl}/images/teams/cde-voleibol-hispano-usera.jpg.jpeg` },
  { id: 48,  name: 'cde voleibol madrid ciudad',            url: `${baseUrl}/images/teams/cde-voleibol-madrid-ciudad.jpg.jpeg` },
  { id: 49,  name: 'cde voleibol san fernando',             url: `${baseUrl}/images/teams/cde-voleibol-san-fernando.jpg.jpeg` },
  { id: 50,  name: 'cde voleibol soto',                     url: `${baseUrl}/images/teams/cde-voleibol-soto.jpg.jpeg` },
  { id: 51,  name: 'cde voleibol valdemoro',                url: `${baseUrl}/images/teams/cde-voleibol-valdemoro.jpg.jpeg` },
  { id: 52,  name: 'cde voley playa madrid',                url: `${baseUrl}/images/teams/cde-voley-playa-madrid.jpg.jpeg` },
  { id: 53,  name: 'cde yma sports',                        url: `${baseUrl}/images/teams/cde-yma-sports.jpg.jpeg` },
  { id: 54,  name: 'cdev maria rodrigo',                    url: `${baseUrl}/images/teams/cdev-maria-rodrigo.jpg` },
  { id: 55,  name: 'ceu san pablo sanchinarro',             url: `${baseUrl}/images/teams/ceu-san-pablo-sanchinarro.jpeg` },
  { id: 56,  name: 'club irlandesas',                       url: `${baseUrl}/images/teams/club-irlandesas.jpg.jpeg` },
  { id: 57,  name: 'club nuestra senora del pilar',         url: `${baseUrl}/images/teams/club-nuestra-senora-del-pilar.jpg.jpeg` },
  { id: 58,  name: 'club saint louis des francais',         url: `${baseUrl}/images/teams/club-saint-louis-des-francais.jpg.jpeg` },
  { id: 59,  name: 'club salesianos san miguel',            url: `${baseUrl}/images/teams/club-salesianos-san-miguel.jpg.jpeg` },
  { id: 60,  name: 'club unificado voleibol alcorcon cuva', url: `${baseUrl}/images/teams/club-unificado-voleibol-alcorcon-cuva.jpg.jpeg` },
  { id: 61,  name: 'club voleibol plaza castilla',          url: `${baseUrl}/images/teams/club-voleibol-plaza-castilla.jpg` },
  { id: 62,  name: 'colegio americano',                     url: `${baseUrl}/images/teams/colegio-americano.jpg.jpeg` },
  { id: 63,  name: 'colegio fuentelarreyna',                url: `${baseUrl}/images/teams/colegio-fuentelarreyna.jpg.jpeg` },
  { id: 64,  name: 'colegio miramadrid',                    url: `${baseUrl}/images/teams/colegio-miramadrid.png` },
  { id: 65,  name: 'corazonistas',                          url: `${baseUrl}/images/teams/corazonistas.jpg.jpeg` },
  { id: 66,  name: 'cv alcala',                             url: `${baseUrl}/images/teams/cv-alcala.jpg.jpeg` },
  { id: 67,  name: 'cv alcobendas',                         url: `${baseUrl}/images/teams/cv-alcobendas.jpg.jpeg` },
  { id: 68,  name: 'cv aranjuez',                           url: `${baseUrl}/images/teams/cv-aranjuez.jpg.jpeg` },
  { id: 69,  name: 'cv arganda',                            url: `${baseUrl}/images/teams/cv-arganda.jpg.jpeg` },
  { id: 70,  name: 'cv bernadette',                         url: `${baseUrl}/images/teams/cv-bernadette.png` },
  { id: 71,  name: 'cv collado villalba',                   url: `${baseUrl}/images/teams/cv-collado-villalba.jpg` },
  { id: 72,  name: 'cv colmenar',                           url: `${baseUrl}/images/teams/cv-colmenar.jpg.jpeg` },
  { id: 73,  name: 'cv coslada',                            url: `${baseUrl}/images/teams/cv-coslada.jpg.jpeg` },
  { id: 74,  name: 'cv cubas',                              url: `${baseUrl}/images/teams/cv-cubas.webp` },
  { id: 75,  name: 'cv daganzo de arriba',                  url: `${baseUrl}/images/teams/cv-daganzo-de-arriba.jpg.jpeg` },
  { id: 76,  name: 'cv el escorial',                        url: `${baseUrl}/images/teams/cv-el-escorial.jpg.jpeg` },
  { id: 77,  name: 'cv esther gonzalez',                    url: `${baseUrl}/images/teams/cv-esther-gonzalez.jpg` },
  { id: 78,  name: 'cv fuenlabrada',                        url: `${baseUrl}/images/teams/cv-fuenlabrada.jpg.jpeg` },
  { id: 79,  name: 'cv fuente el saz crows',                url: `${baseUrl}/images/teams/cv-fuente-el-saz-crows.png` },
  { id: 80,  name: 'cv fuente el saz',                      url: `${baseUrl}/images/teams/cv-fuente-el-saz.webp` },
  { id: 81,  name: 'cv guadarrama',                         url: `${baseUrl}/images/teams/cv-guadarrama.jpg.jpeg` },
  { id: 82,  name: 'cv las rozas',                          url: `${baseUrl}/images/teams/cv-las-rozas.jpg.jpeg` },
  { id: 83,  name: 'cv leganes',                            url: `${baseUrl}/images/teams/cv-leganes.jpg.jpeg` },
  { id: 84,  name: 'cv majadahonda',                        url: `${baseUrl}/images/teams/cv-majadahonda.jpg.jpeg` },
  { id: 85,  name: 'cv maria rodrigo',                      url: `${baseUrl}/images/teams/cv-maria-rodrigo.png` },
  { id: 86,  name: 'cv moralzarzal',                        url: `${baseUrl}/images/teams/cv-moralzarzal.jpg.jpeg` },
  { id: 87,  name: 'cv mostoles',                           url: `${baseUrl}/images/teams/cv-mostoles.jpg` },
  { id: 88,  name: 'cv next generation ng madrid',          url: `${baseUrl}/images/teams/cv-next-generation-ng-madrid.jpg` },
  { id: 89,  name: 'cv nueva castilla',                     url: `${baseUrl}/images/teams/cv-nueva-castilla.jpg.jpeg` },
  { id: 90,  name: 'cv paraiso sagrados corazones',         url: `${baseUrl}/images/teams/cv-paraiso-sagrados-corazones.jpg` },
  { id: 91,  name: 'cv pinto',                              url: `${baseUrl}/images/teams/cv-pinto.jpg.jpeg` },
  { id: 92,  name: 'cv sanse',                              url: `${baseUrl}/images/teams/cv-sanse.jpg.jpeg` },
  { id: 93,  name: 'cv torrejon',                           url: `${baseUrl}/images/teams/cv-torrejon.jpg.jpeg` },
  { id: 94,  name: 'cv torrelodones',                       url: `${baseUrl}/images/teams/cv-torrelodones.jpg.jpeg` },
  { id: 95,  name: 'cv tres cantos',                        url: `${baseUrl}/images/teams/cv-tres-cantos.jpg.jpeg` },
  { id: 96,  name: 'cv valdetorre',                         url: `${baseUrl}/images/teams/cv-valdetorre.jpg` },
  { id: 97,  name: 'cv velilla',                            url: `${baseUrl}/images/teams/cv-velilla.jpg.jpeg` },
  { id: 98,  name: 'cv villanueva del pardillo',            url: `${baseUrl}/images/teams/cv-villanueva-del-pardillo.jpg.jpeg` },
  { id: 99,  name: 'europa voleibol',                       url: `${baseUrl}/images/teams/europa-voleibol.png` },
  { id: 100, name: 'gmadrid sports',                        url: `${baseUrl}/images/teams/gmadrid-sports.jpg.jpeg` },
  { id: 101, name: 'highlands los fresnos',                 url: `${baseUrl}/images/teams/highlands-los-fresnos.png` },
  { id: 102, name: 'ie university',                         url: `${baseUrl}/images/teams/ie-university.png` },
  { id: 103, name: 'madrid beach voley academy',            url: `${baseUrl}/images/teams/madrid-beach-voley-academy.jpg.jpeg` },
  { id: 104, name: 'marianistas amoros',                    url: `${baseUrl}/images/teams/marianistas-amoros.jpg.jpeg` },
  { id: 105, name: 'mintonette cv pozuelo',                 url: `${baseUrl}/images/teams/mintonette-cv-pozuelo.jpg.jpeg` },
  { id: 106, name: 'mirasur school pinto',                  url: `${baseUrl}/images/teams/mirasur-school-pinto.png` },
  { id: 107, name: 'padre manyanet alcobendas',             url: `${baseUrl}/images/teams/padre-manyanet-alcobendas.webp` },
  { id: 108, name: 'saco chamartin',                        url: `${baseUrl}/images/teams/saco-chamartin.jpg` },
  { id: 109, name: 'sad colegio claret',                    url: `${baseUrl}/images/teams/sad-colegio-claret.jpg.jpeg` },
  { id: 110, name: 'sad colegio internacional kolbe',       url: `${baseUrl}/images/teams/sad-colegio-internacional-kolbe.jpg.jpeg` },
  { id: 111, name: 'sad recuerdo',                          url: `${baseUrl}/images/teams/sad-recuerdo.jpg.jpeg` },
  { id: 112, name: 'san agustin guadalix',                  url: `${baseUrl}/images/teams/san-agustin-guadalix.png` },
  { id: 113, name: 'san agustin',                           url: `${baseUrl}/images/teams/san-agustin.jpg.jpeg` },
  { id: 114, name: 'sek el castillo',                       url: `${baseUrl}/images/teams/sek-el-castillo.webp` },
  { id: 115, name: 'st michaels school',                    url: `${baseUrl}/images/teams/st-michaels-school.png` },
  { id: 116, name: 'stars sport madrid',                    url: `${baseUrl}/images/teams/stars-sport-madrid.jpg` },
  { id: 117, name: 'stars sport volley',                    url: `${baseUrl}/images/teams/stars-sport-volley.jpg.jpeg` },
  { id: 118, name: 'ud loeches',                            url: `${baseUrl}/images/teams/ud-loeches.jpg` },
];

export default staticImages;
